version: "3.9"

services:
  mysqldb:
    image: mysql:8.0.36
    environment:
      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - sneakers-net
  app:
    build: ./
    image: ghcr.io/lamphamit/sneakers:latest
    environment:
      - SLEEP_LENGTH=5
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/sneakers
      - spring.datasource.username=root
      - spring.datasource.password=admin
      - spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
    ports:
      - "8080:8080"
    networks:
      - sneakers-net
    depends_on:
      - mysqldb
    restart: on-failure

networks:
  sneakers-net:
    driver: bridge
    name: snea  kers net

volumes:
  mysql-volume:
