name: SNEAKERS CI
on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "**"
  push:
    branches: [ "main" ]
    paths:
      - "**"

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache local Maven repository
        uses: actions/cache@v4.0.2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Cache Sonarcloud packages
        uses: actions/cache@v4.0.2
        with:
          path: ~/.sonar
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Run Maven Build Command
        run: mvn clean install -DskipTests
      - name: Run Maven Test
        run: mvn test
      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit-Test-Results
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
      - name: Analyze with Sonarcloud
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository || github.ref == 'refs/heads/main' }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -f product
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: v0.7.0
      - name: Login container registry
        if: ${{ github.refs == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_LOGIN_TOKEN }}
      - name: Build and push docker image
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/lamphamit/sneakers:latest